name: challenge01
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  job1:
    name: Print Date - Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Run Date Command
      run: date
  job2:
    name: Print Date - Windows
    runs-on: windows-latest
    steps:
    - name: Run Date Command
      run: date
  job3:
    name: Third Job
    runs-on: macos-latest
    steps:
    - name: Run Date Command
      run: date
  job4:
    name: Fourth Job
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Done!